-- Public storage bucket for write-time-generated OG preview PNGs.
--
-- Each mixtape gets one object at `og-images/{handle}.png`, generated by the
-- `render-og` Edge Function whenever a write affects the artist line. The
-- bucket is public-read so social-platform preview engines can fetch the
-- image without authentication; only the service role (used by the Edge
-- Function) can write.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'og-images',
  'og-images',
  true,
  1048576,                    -- 1 MiB ceiling; our renders are ~30-80 KB
  array['image/png']
)
on conflict (id) do update
  set public = excluded.public,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

-- Storage object policies live on the `storage.objects` table. Service-role
-- writes bypass RLS; we just need a public-read policy for the bucket.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage' and tablename = 'objects'
    and policyname = 'og_images_public_read'
  ) then
    create policy og_images_public_read
      on storage.objects for select
      to public
      using (bucket_id = 'og-images');
  end if;
end $$;
